version: "3.3"
services:
  app:
    image: bitwalker/alpine-elixir-phoenix:1.10.3
    ports:
      - 8888:8888
    depends_on:
      - postgres
    volumes:
      - ./:/opt/app
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game_journal_dev
    restart: always
    ports:
      - 5432:5432

volumes:
  postgres:
    driver: local
