FROM elixir:1.10
RUN mix local.hex --force
RUN mix local.rebar --force

WORKDIR /bin
RUN wget -q "https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh"
RUN chmod +x ./wait-for-it.sh

WORKDIR /app
CMD ["/bin/wait-for-it.sh", "-t", "0", "postgres:5432", "--", "mix phx.server"]
