version: "3.3"
services:
  webapp:
    image: bitwalker/alpine-elixir-phoenix:1.10.3
    ports:
      - 4000:4000
    depends_on: 
      - postgres
    volumes:
      - ./:/app
    entrypoint: "/app/dev.sh"
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game_journal_dev
    restart: always

volumes:
  postgres:
    driver: local
